import { scenarios } from "./data.js";
import { buildSessionInsights, summarize } from "./coach.js";
import { buildGrowthCalendar } from "./progress.js";
import { appendTurnTranscript, createAudioCapture, recognitionTranscript, translateCoachText } from "./voice.js";
import { createSpeechAssessmentClient } from "./speech-assessment.js";
import { createAiCoachClient } from "./ai-coach.js";
import { createTranscriptionClient, prepareLocalRecognition } from "./transcription.js";
import { callPhaseCopy, createVoiceActivityGate } from "./phone-call.js";
import { contextualAnswerSupport, normalizeAnswerSupport } from "./answer-support.js";

const state = { view: "home", scenario: null, sessionId: 0, messages: [], answerQueue: [], processingAnswer: false, elapsed: 0, timer: null, recognition: null, recognitionRestartTimer: null, recognitionSilenceTimer: null, recognitionUnavailable: false, localRecognition: false, callActive: false, callPhase: "connecting", callAutoTimer: null, callDetector: null, voiceTurnActive: false, voiceFinalizing: false, voiceStopRequested: false, voiceTurnStartedAt: null, voiceTranscript: "", voiceConfidence: [], voiceError: "", voiceCaptureStatus: "idle", audioCaptureRequestId: 0, audioCapturePromise: null, interim: "", coachSpeaking: false, coachPaused: false, audioCapture: null, audioCaptureFactory: window.FLUENTLOOP_AUDIO_CAPTURE_FACTORY || createAudioCapture, sessionAudioUrl: null, aiBusy: false, aiMode: "checking", aiProvider: null, aiModel: null, assessmentClient: createSpeechAssessmentClient(window.FLUENTLOOP_SPEECH_SERVICE || { endpoint: "/api/pronunciation" }), transcriber: createTranscriptionClient(window.FLUENTLOOP_TRANSCRIPTION_SERVICE || { endpoint: "/api/transcribe" }), aiCoach: createAiCoachClient() };
const app = document.querySelector("#app");
const safe = value => String(value ?? "").replace(/[&<>"']/g, character => ({
  "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"
})[character]);
const header = () => {
  const history = JSON.parse(localStorage.getItem("fluentloop-history") || "[]");
  const streak = buildGrowthCalendar(history).streak;
  return `<header><button class="brand" data-home><b>F</b> FluentLoop</button><nav>练习场景　 学习方法　 成长记录</nav><span class="streak">● <b>${streak}</b> 天连续练习</span></header>`;
};

function home() {
  const history = JSON.parse(localStorage.getItem("fluentloop-history") || "[]");
  app.innerHTML = `${header()}<main>
    <section class="hero"><div class="hero-copy"><label>● AI-POWERED SPEAKING STUDIO</label><h1>把每一次开口，<em>变成真实进步。</em></h1><p>沉浸式场景对话、即时智能纠错和可量化成长报告，让英语口语练习更自然、更有效。</p><button class="primary" data-start>开始练习 →</button></div>
    <div class="visual"><div class="orb"></div><article class="coach-card"><div class="coach-title"><i>FL</i><span><b>Fluent Coach</b><small>● Ready to practice</small></span></div><h2>“Tell me about a challenge you solved at work.”</h2><div class="wave">${"<i></i>".repeat(24)}</div><footer><span><b>86</b> Fluency</span><span><b>92</b> Grammar</span><span><b>84</b> Pronunciation</span></footer></article></div></section>
    <section class="scenes" id="scenes"><div class="section-title"><span><label>CHOOSE A SCENE</label><h2>今天想练什么？</h2></span><p>每个场景都由 AI 扮演真实角色，并根据你的水平动态追问。</p></div><div class="scene-grid">${scenarios.map(card).join("")}</div></section>
    <section class="loop"><div><label>LEARNING LOOP</label><h2>不只告诉你哪里错，<br>更告诉你如何变好。</h2></div><div class="steps"><article><b>01</b><h3>自然对话</h3><p>AI 根据上下文追问，避免背答案式练习。</p></article><article><b>02</b><h3>适时反馈</h3><p>不中断表达，回答结束后再给精准建议。</p></article><article><b>03</b><h3>量化成长</h3><p>持续追踪流利度、语法、词汇和发音。</p></article></div></section>
    ${growthCalendar(history)}
    ${history.length ? `<section class="history"><label>YOUR PROGRESS</label><h2>持续练习，变化看得见</h2><article><span><small>最近一次</small><b>${history[0].scenario}</b></span><strong>${history[0].overall}<small>综合得分</small></strong><span><b>↗ 保持练习</b><small>下一次会更自然</small></span></article></section>` : ""}
    </main>${pageFooter()}`;
  document.querySelector("[data-start]").onclick = () => document.querySelector("#scenes").scrollIntoView({behavior:"smooth"});
  document.querySelectorAll("[data-scene]").forEach(el => el.onclick = () => start(el.dataset.scene));
  bindHome();
}

function growthCalendar(history) {
  const calendar = buildGrowthCalendar(history);
  const weekdays = ["日", "一", "二", "三", "四", "五", "六"];
  return `<section class="growth-calendar">
    <div class="calendar-heading"><div><label>DAILY GROWTH</label><h2>练习日历</h2><p>完成一次口语练习，即可点亮当天成长记录。</p></div>
    <div class="calendar-stats"><span><b>${calendar.streak}</b>连续天数</span><span><b>${calendar.activeDays}</b>本月签到</span><span><b>${calendar.totalWords}</b>累计单词</span></div></div>
    <article class="calendar-card"><header><b>${calendar.label}</b><small>${calendar.activeDays ? "坚持正在发生，继续保持。" : "完成今天的第一场练习吧。"}</small></header>
    <div class="weekdays">${weekdays.map(day => `<span>${day}</span>`).join("")}</div>
    <div class="calendar-grid">${calendar.cells.map(cell => cell ? `<div class="calendar-day ${cell.activity ? "checked" : ""} ${cell.isToday ? "today" : ""}" title="${cell.activity ? `${cell.activity.sessions} 次练习 · 最高 ${cell.activity.bestScore} 分` : "尚未练习"}"><span>${cell.day}</span>${cell.activity ? `<i>✓</i><small>${cell.activity.bestScore}</small>` : ""}</div>` : "<div></div>").join("")}</div></article>
  </section>`;
}

const card = s => `<article class="scene" data-scene="${s.id}" style="--accent:${s.color}"><div><i>${s.icon}</i><small>${s.level}</small></div><h3>${s.title}</h3><label>${s.en}</label><p>${s.description}</p><footer><span>◷ ${s.time}</span><b>开始 →</b></footer></article>`;

function practice() {
  const s = state.scenario, last = [...state.messages].reverse().find(m => m.role === "user"), coachMessage = [...state.messages].reverse().find(m=>m.role==="coach"), coachPrompt = coachMessage?.text || s.opening, answerSupport = normalizeAnswerSupport(coachMessage?.support, contextualAnswerSupport(s, coachPrompt)), [callTitle,callDetail]=callPhaseCopy(state.callPhase);
  app.innerHTML = `${header()}<main class="practice"><aside><button class="back" data-home>← 返回场景</button><div class="current" style="--accent:${s.color}"><i>${s.icon}</i><span><small>当前场景</small><b>${s.title}</b><label>${s.en}</label></span></div><div class="goal"><small>本次目标</small><p>${s.goal}</p></div><div class="live"><small>实时表现</small>${mini("流利度",last?.analysis.scores.fluency)}${mini("语法",last?.analysis.scores.grammar)}${mini("词汇",last?.analysis.scores.vocabulary)}${mini("语音清晰度",last?.analysis.scores.pronunciation)}</div><button class="finish" data-finish>结束练习并查看报告</button></aside>
  <section class="conversation"><div class="conv-head"><span>● <b>AI 场景语音通话</b><small>AI 说完后自动聆听；你停顿约 1 秒后自动发送</small></span><div class="voice-status"><em class="ai-mode ${state.aiMode}">${state.aiMode === "ai" ? `${safe(state.aiProvider || "AI")} · ${safe(state.aiModel || "CONTEXT COACH")}` : state.aiMode === "offline" ? "OFFLINE FALLBACK" : "AI CHECKING"}</em><b id="timer">${format(state.elapsed)}</b></div></div><div class="call-stage ${state.callPhase}"><div class="call-orb"><i>${s.icon}</i><span>${"<b></b>".repeat(18)}</span></div><small>${safe(s.en)}</small><h2>${safe(callTitle)}</h2><p>${safe(callDetail)}</p><div class="call-actions"><button data-voice-turn ${state.aiBusy || state.coachSpeaking || state.voiceFinalizing ? "disabled" : ""}>${state.voiceFinalizing?"正在提交…":state.voiceTurnActive?"结束本轮":"继续通话"}</button><button class="hangup" data-finish>挂断并查看报告</button></div></div><div class="messages">${state.messages.map(message).join("")}${state.aiBusy ? `<div class="listening ai-thinking"><b>AI Coach 正在理解上下文</b><span>正在生成角色回应与语境化纠错...</span></div>` : ""}${state.voiceTurnActive ? `<div class="listening voice-turn"><b>● 正在听你说</b><span>${safe(appendTurnTranscript(state.voiceTranscript,state.interim) || "请自然说英语；检测到停顿后会自动发送，也可手动结束本轮。")}</span><small class="capture-status ${state.voiceCaptureStatus}">${state.voiceCaptureStatus==="ready"?"麦克风录音已就绪，可生成发音评测":state.voiceCaptureStatus==="requesting"?"正在连接麦克风；文字转写已先行启动":state.voiceCaptureStatus==="unavailable"?"麦克风录音不可用；可使用文字回答":""}</small>${state.voiceError?`<small class="capture-status unavailable">${safe(state.voiceError)}</small>`:""}</div>` : state.voiceError ? `<div class="listening voice-error"><b>语音录入提示</b><span>${safe(state.voiceError)}</span></div>` : ""}</div><div class="composer"><section class="answer-support ${state.voiceTurnActive?"active":""}"><div><small>${coachMessage?.support ? "AI 实时建议 · 根据当前问题更新" : "上下文回答建议 · 通话中也可参考"}</small><b>${safe(coachPrompt)}</b></div><div class="support-starters">${answerSupport.starters.map(item=>`<span>${safe(item)}</span>`).join("")}</div><p><strong>自然示例</strong>${safe(answerSupport.example)}</p><footer>${answerSupport.keywords.map(item=>`<i>${safe(item)}</i>`).join("")}</footer></section><div><button data-demo ${state.voiceTurnActive || state.voiceFinalizing ? "disabled" : ""}>填入纠错示例</button><input placeholder="语音不可用时，也可以输入英文回答…" ${state.aiBusy || state.voiceTurnActive || state.voiceFinalizing ? "disabled" : ""}><button data-send ${state.aiBusy || state.voiceTurnActive || state.voiceFinalizing ? "disabled" : ""}>↑</button></div></div></section></main>`;
  bindHome(); document.querySelectorAll("[data-finish]").forEach(button=>button.onclick=finish);
  document.querySelector("[data-demo]").onclick=()=>document.querySelector("input").value=s.demo;
  document.querySelector("[data-send]").onclick=send; document.querySelector("input").onkeydown=e=>e.key==="Enter"&&send();
  document.querySelector("[data-voice-turn]").onclick=()=>toggleVoiceTurn(true); document.querySelectorAll("[data-speak]").forEach(b=>b.onclick=()=>speak(decodeURIComponent(b.dataset.speak),false));
  document.querySelectorAll("[data-speech-pause]").forEach(b=>b.onclick=pauseCoach);
  document.querySelectorAll("[data-speech-resume]").forEach(b=>b.onclick=resumeCoach);
  document.querySelectorAll("[data-speech-stop]").forEach(b=>b.onclick=stopCoach);
  requestAnimationFrame(()=>{ const el=document.querySelector(".messages"); el.scrollTop=el.scrollHeight; });
}
const mini=(name,value=0)=>`<div><span>${name}</span><i><b style="width:${value}%"></b></i><strong>${value||"—"}</strong></div>`;
const message=m=>m.role==="coach"?`<article class="msg coach"><i>FL</i><div><small>FLUENT COACH</small><p>${safe(m.text)}</p><p class="translation">${safe(m.translation || translateCoachText(m.text,state.scenario?.id))}</p><div class="speech-controls"><button data-speak="${encodeURIComponent(m.text)}">▶ 播放</button><button data-speech-pause>Ⅱ 暂停</button><button data-speech-resume>▷ 继续</button><button data-speech-stop>■ 停止</button></div></div></article>`:
`<article class="msg user"><div><small>YOU ${m.analysis.assessmentMode === "ai" ? "· AI REVIEWED" : "· OFFLINE REVIEW"}</small><p>${safe(m.text)}</p><section class="feedback"><strong>${m.analysis.scores.overall}</strong><span><b>${safe(m.analysis.encouragement || (m.analysis.corrections.length?"表达清晰，留意下面的小调整。":"表达自然且清晰，句型使用得很好。"))}</b><small>${m.analysis.wpm} WPM · ${m.analysis.words} words · ${safe(m.analysis.scoringEvidence?.confidence || "low")} confidence</small></span>${m.analysis.latency?`<div class="latency"><span>首字节 ${m.analysis.latency.firstByteMs??"—"}ms</span><span>AI ${m.analysis.latency.aiMs}ms</span><span>发音评测 ${m.analysis.latency.assessmentMs??0}ms</span><span>本轮总计 ${m.analysis.latency.totalMs}ms</span></div>`:""}<div class="score-reasons">${(m.analysis.scoringEvidence?.reasons || []).map(reason=>`<small>${safe(reason)}</small>`).join("")}</div>${m.analysis.speechEvidence ? speechEvidence(m.analysis.speechEvidence,m.analysis.scores.pronunciation) : `<div class="evidence muted"><b>未进行语音评测</b><small>文字输入不会生成发音或语音清晰度分数。</small></div>`}${m.analysis.corrections.map(c=>`<article><label>表达建议</label><del>${safe(c.original)}</del><b>→ ${safe(c.improved)}</b><small>${safe(c.reason)}</small></article>`).join("")||"<em>✓ 本轮没有发现明显语法问题</em>"}</section></div><i>YOU</i></article>`;
const speechEvidence=(evidence,score)=>`<div class="evidence"><b>${evidence.level==="phoneme"?"Azure 音素级评测":"浏览器清晰度代理"} · ${score}</b>${evidence.level==="phoneme"?`<div class="speech-dimensions"><span>准确度 ${evidence.accuracy}</span><span>流利度 ${evidence.fluency}</span><span>完整度 ${evidence.completeness}</span>${Number.isFinite(evidence.prosody)?`<span>韵律 ${evidence.prosody}</span>`:""}</div><div class="word-diagnostics">${evidence.words.filter(word=>word.score<80||word.errorType!=="None").slice(0,6).map(word=>`<span><b>${safe(word.word)} ${word.score}</b><small>${safe(word.errorType)}</small>${word.phonemes?.filter(p=>p.score<80).slice(0,4).map(p=>`<i>/${safe(p.phoneme)}/ ${p.score}</i>`).join("")||""}</span>`).join("")||"<small>本轮没有发现明显单词或音素问题。</small>"}</div>`:""}<small>${safe(evidence.fallbackReason||evidence.disclaimer)}</small></div>`;

function report() {
  const r=summarize(state.messages), s=state.scenario;
  const history=JSON.parse(localStorage.getItem("fluentloop-history")||"[]"),insights=buildSessionInsights(state.messages,s,history.slice(1));
  app.innerHTML=`${header()}<main class="report"><section class="report-top"><div><label>● SESSION COMPLETE</label><h1>很棒，你完成了<br><em>${s.title}</em>练习。</h1><p>${safe(insights.trend)}</p></div><div class="ring" style="--score:${r.overall}"><span><b>${r.overall||"--"}</b><small>综合得分</small></span></div></section><section class="metrics">${metric("流利度",r.fluency)}${metric("语法准确度",r.grammar)}${metric("词汇丰富度",r.vocabulary)}${metric("语音清晰度",r.pronunciation)}</section>${state.sessionAudioUrl ? `<section class="audio-review"><label>SESSION AUDIO</label><h2>回听本次口语录音</h2><audio controls src="${state.sessionAudioUrl}"></audio><p>录音仅保存在当前浏览器内存中，刷新页面后自动清除。</p></section>` : ""}<section class="details"><article><label>PERSONAL INSIGHTS</label><h2>本次练习洞察</h2><div class="stats"><span><b>${r.turns}</b>轮对话</span><span><b>${r.words}</b>个单词</span><span><b>${r.wpm}</b>WPM</span><span><b>${r.corrections}</b>个建议</span></div><p class="note"><b>优势</b>${safe(insights.strength)}</p><p class="note"><b>重点</b>${safe(insights.focus)}</p><p class="note"><b>复练</b>${safe(insights.correction)}</p></article><aside><label>NEXT STEP</label><h2>把建议变成能力</h2><p>${safe(insights.nextTask)}</p><button data-retry>再练一次 →</button><button data-home>选择其他场景</button></aside></section></main>${pageFooter()}`;
  document.querySelector("[data-retry]").onclick=()=>start(s.id); bindHome();
}
const metric=(name,score)=>`<article><span><small>${name}</small><b>${Number.isFinite(score)?score:"N/A"}</b></span><i><b style="width:${Number.isFinite(score)?score:0}%"></b></i><p>${Number.isFinite(score)?"保持练习，下一次表达会更自然。":"仅语音回答可获得此项评测。"}</p></article>`;

async function start(id){ state.sessionId++;const sessionId=state.sessionId;state.answerQueue=[];state.scenario=scenarios.find(s=>s.id===id); state.messages=[{role:"coach",text:state.scenario.opening,translation:translateCoachText(state.scenario.opening,id)}]; state.view="practice";resetVoiceTurn();state.callActive=true;state.callPhase="connecting";state.sessionAudioUrl=null; state.elapsed=0;clearInterval(state.timer);state.timer=setInterval(()=>{state.elapsed++;const t=document.querySelector("#timer");if(t)t.textContent=format(state.elapsed)},1000);practice();setTimeout(()=>{if(state.view==="practice"&&state.sessionId===sessionId)speak(state.scenario.opening,true)},300)}
function handleAnswer(text,seconds,speechEvidence=null,timing={}){return new Promise(resolve=>{state.answerQueue.push({text,seconds,speechEvidence,timing:{startedAt:timing.startedAt??performance.now(),assessmentMs:timing.assessmentMs??0},sessionId:state.sessionId,resolve});processAnswerQueue()})}
async function processAnswerQueue(){if(state.processingAnswer)return;const item=state.answerQueue.shift();if(!item)return;if(item.sessionId!==state.sessionId||state.view!=="practice"){item.resolve(false);return processAnswerQueue()}state.processingAnswer=true;state.aiBusy=true;state.callPhase="thinking";practice();try{const result=await state.aiCoach.respond({scenario:state.scenario,messages:state.messages,text:item.text,seconds:item.seconds,speechEvidence:item.speechEvidence});if(item.sessionId!==state.sessionId||state.view!=="practice"){item.resolve(false);return}state.aiMode=result.mode;state.aiProvider=result.provider;state.aiModel=result.model;result.analysis.latency={...result.latency,assessmentMs:item.timing.assessmentMs,totalMs:Math.round(performance.now()-item.timing.startedAt)};state.messages.push({role:"user",text:item.text,analysis:result.analysis},{role:"coach",...result.coach});item.resolve(true);practice();speak(result.coach.text,true)}finally{state.processingAnswer=false;state.aiBusy=false;if(state.view==="practice")practice();processAnswerQueue()}}
function send(){const input=document.querySelector("input"),text=input.value.trim();if(!text)return;state.callPhase="thinking";handleAnswer(text,Math.max(7,text.split(/\s+/).length/1.8))}
function clearCallAutoDetection(){clearInterval(state.callAutoTimer);state.callAutoTimer=null;state.callDetector=null}
function startCallAutoDetection(){clearCallAutoDetection();state.callDetector=createVoiceActivityGate();let lastTranscript="";state.callAutoTimer=setInterval(()=>{if(!state.callActive||!state.voiceTurnActive||state.voiceFinalizing)return clearCallAutoDetection();const transcript=appendTurnTranscript(state.voiceTranscript,state.interim),hasTranscript=Boolean(transcript&&transcript!==lastTranscript);lastTranscript=transcript;const result=state.callDetector.update({...state.audioCapture?.snapshot(20),hasTranscript});if(result.shouldFinish)requestVoiceTurnFinish()},250)}
function resetVoiceTurn(){clearTimeout(state.recognitionRestartTimer);state.recognitionRestartTimer=null;clearTimeout(state.recognitionSilenceTimer);state.recognitionSilenceTimer=null;clearCallAutoDetection();state.audioCaptureRequestId++;state.recognition=null;state.recognitionUnavailable=false;state.voiceTurnActive=false;state.voiceFinalizing=false;state.voiceStopRequested=false;state.voiceTurnStartedAt=null;state.voiceTranscript="";state.voiceConfidence=[];state.voiceError="";state.voiceCaptureStatus=state.audioCapture?"ready":"idle";state.interim=""}
async function toggleVoiceTurn(requestPermission=false){if(state.voiceTurnActive)return requestVoiceTurnFinish();await beginVoiceTurn({requestPermission})}
async function beginVoiceTurn({requestPermission=false}={}){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR&&!navigator.mediaDevices?.getUserMedia){state.voiceError="当前浏览器无法录音，请检查麦克风权限，或改用文字输入。";state.callPhase="ready";practice();return}if(state.coachSpeaking||state.aiBusy||state.voiceFinalizing)return;if(!state.audioCapture&&navigator.mediaDevices?.getUserMedia){if(!requestPermission){state.voiceError="请点击“继续通话”并允许麦克风权限，然后开始说英语。";state.callPhase="ready";practice();return}state.voiceCaptureStatus="requesting";state.voiceError="正在请求麦克风权限，请在浏览器提示中选择允许。";state.callPhase="connecting";practice();const capture=await ensureVoiceAudioCapture();if(!capture){state.voiceError="麦克风无法启动。请检查浏览器地址栏中的麦克风权限和系统输入设备，或使用文字回答。";state.callPhase="ready";practice();return}}state.voiceTurnActive=true;state.callPhase="listening";state.voiceStopRequested=false;state.recognitionUnavailable=false;state.voiceTurnStartedAt=performance.now();state.voiceTranscript="";state.voiceConfidence=[];state.voiceError="";state.voiceCaptureStatus=state.audioCapture?"ready":"unavailable";state.interim="";state.audioCapture?.beginUtterance();practice();if(SR){prepareLocalRecognition(SR).then(available=>{state.localRecognition=available});startTurnRecognition()}startCallAutoDetection();clearTimeout(state.recognitionSilenceTimer);state.recognitionSilenceTimer=setTimeout(()=>{if(state.voiceTurnActive&&!state.voiceTranscript&&!state.interim){state.recognitionUnavailable=true;state.voiceError=state.audioCapture?"浏览器实时转写无响应。请说完后点击“结束本轮”，系统将尝试使用录音转写；也可改用文字回答。":"浏览器实时转写无响应，请使用文字回答。";if(state.recognition){try{state.recognition.stop()}catch{}}state.recognition=null;practice()}},10000)}
function ensureVoiceAudioCapture(){if(state.audioCapture)return Promise.resolve(state.audioCapture);if(state.audioCapturePromise)return state.audioCapturePromise;const requestId=++state.audioCaptureRequestId,sessionId=state.sessionId;state.audioCapturePromise=state.audioCaptureFactory().then(capture=>{if(requestId!==state.audioCaptureRequestId||sessionId!==state.sessionId||state.view!=="practice"){capture.stop();return null}state.audioCapture=capture;state.voiceCaptureStatus="ready";return capture}).catch(()=>{if(requestId===state.audioCaptureRequestId&&sessionId===state.sessionId)state.voiceCaptureStatus="unavailable";return null}).finally(()=>{state.audioCapturePromise=null;if(state.view==="practice")practice()});return state.audioCapturePromise}
function startTurnRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!state.voiceTurnActive||state.voiceStopRequested||state.recognitionUnavailable||state.recognition||!SR)return;const rec=new SR();rec.lang="en-US";rec.interimResults=true;rec.continuous=true;rec.maxAlternatives=1;if(state.localRecognition)rec.processLocally=true;state.recognition=rec;rec.onresult=e=>{if(rec!==state.recognition)return;const transcript=recognitionTranscript(Array.from(e.results).slice(e.resultIndex));state.voiceTranscript=appendTurnTranscript(state.voiceTranscript,transcript.finalText);state.interim=transcript.interimText;state.voiceError="";if(transcript.finalText){clearTimeout(state.recognitionSilenceTimer);state.recognitionSilenceTimer=null;if(Number.isFinite(transcript.confidence))state.voiceConfidence.push(transcript.confidence)}practice()};rec.onnomatch=()=>{state.voiceError="听到了声音，但暂时无法识别为英文。请靠近麦克风、放慢语速后重试。";practice()};rec.onerror=e=>{if(e.error==="language-not-supported")state.localRecognition=false;if(e.error==="no-speech"){state.voiceError="暂未检测到清晰语音，请靠近麦克风后继续说。";practice();return}if(["not-allowed","service-not-allowed","audio-capture","network"].includes(e.error)){state.recognitionUnavailable=true;clearTimeout(state.recognitionSilenceTimer);state.recognitionSilenceTimer=null;state.voiceError="浏览器实时转写不可用，请点击“结束本轮”尝试录音转写，或改用文字回答。";state.recognition=null;practice()} };rec.onend=()=>{if(rec!==state.recognition)return;state.recognition=null;if(state.voiceStopRequested)return completeVoiceTurn();state.voiceTranscript=appendTurnTranscript(state.voiceTranscript,state.interim);state.interim="";if(state.voiceTurnActive){clearTimeout(state.recognitionRestartTimer);state.recognitionRestartTimer=setTimeout(startTurnRecognition,350)}practice()};try{rec.start()}catch{state.recognition=null;state.recognitionUnavailable=true;state.voiceError="浏览器实时转写启动失败，请点击“结束本轮”尝试录音转写，或改用文字回答。";practice()}}
function requestVoiceTurnFinish(){if(!state.voiceTurnActive)return;clearCallAutoDetection();state.callPhase="thinking";state.voiceStopRequested=true;state.voiceTurnActive=false;state.voiceFinalizing=true;clearTimeout(state.recognitionRestartTimer);state.recognitionRestartTimer=null;if(state.recognition)state.recognition.stop();else completeVoiceTurn();practice()}
async function completeVoiceTurn(){if(!state.voiceFinalizing)return;let text=appendTurnTranscript(state.voiceTranscript,state.interim);let confidence=state.voiceConfidence.length?state.voiceConfidence.reduce((sum,value)=>sum+value,0)/state.voiceConfidence.length:0;const seconds=Math.max(1,(performance.now()-(state.voiceTurnStartedAt||performance.now()))/1000);const audioBlob=state.audioCapture?.utteranceBlob()||null;state.voiceStopRequested=false;state.voiceTranscript="";state.voiceConfidence=[];state.interim="";state.voiceTurnStartedAt=null;try{const startedAt=performance.now();if(!text&&audioBlob){state.voiceError="正在使用本地 Whisper 识别本轮录音，首次使用需要下载模型…";practice();const transcript=await state.transcriber.transcribe(audioBlob);text=transcript.text;confidence=transcript.confidence??confidence}if(!text)throw new Error("没有识别到回答，请靠近麦克风并重试。");const assessmentStartedAt=performance.now();const evidence=await state.assessmentClient.assess(audioBlob,text,{confidence,...(state.audioCapture?.snapshot()||{})});await handleAnswer(text,seconds,evidence,{startedAt,assessmentMs:Math.round(performance.now()-assessmentStartedAt)})}catch(error){state.voiceError=error.message||"语音转写失败，请重试或使用文字输入。";if(state.voiceError.includes("transcription")||state.voiceError.includes("转写"))state.voiceError="语音转写暂不可用。请重试或使用文字输入继续练习。";state.callPhase="ready"}finally{state.voiceFinalizing=false;if(state.view==="practice")practice()}}
function speak(text,continueCall=false){if(state.voiceTurnActive)return;clearCallAutoDetection();if(!window.speechSynthesis){if(continueCall&&state.callActive)setTimeout(beginVoiceTurn,250);return}state.callPhase="speaking";state.coachSpeaking=true;state.coachPaused=false;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="en-US";u.rate=.96;u.onend=u.onerror=()=>{state.coachSpeaking=false;state.coachPaused=false;state.callPhase="ready";practice();if(continueCall&&state.callActive)setTimeout(beginVoiceTurn,300)};speechSynthesis.speak(u);practice()}
function pauseCoach(){if(!speechSynthesis?.speaking)return;speechSynthesis.pause();state.coachPaused=true;practice()}
function resumeCoach(){if(!speechSynthesis?.paused)return;speechSynthesis.resume();state.coachPaused=false;practice()}
function stopCoach(){speechSynthesis?.cancel();state.coachSpeaking=false;state.coachPaused=false;state.callPhase="ready";practice()}
async function finish(){state.callActive=false;state.callPhase="ended";state.sessionId++;state.answerQueue.splice(0).forEach(item=>item.resolve(false));await stopVoiceSession(true);clearInterval(state.timer);const r=summarize(state.messages),h=JSON.parse(localStorage.getItem("fluentloop-history")||"[]");h.unshift({...r,scenario:state.scenario.title,date:new Date().toISOString()});localStorage.setItem("fluentloop-history",JSON.stringify(h.slice(0,180)));state.view="report";report()}
async function stopVoiceSession(keepRecording=false){state.callActive=false;clearCallAutoDetection();clearTimeout(state.recognitionRestartTimer);state.voiceTurnActive=false;state.voiceStopRequested=false;state.recognition?.stop();resetVoiceTurn();state.coachSpeaking=false;state.coachPaused=false;speechSynthesis?.cancel();if(state.audioCapture){const blob=await state.audioCapture.stop();if(keepRecording)state.sessionAudioUrl=URL.createObjectURL(blob);state.audioCapture=null}state.audioCapturePromise=null}
function bindHome(){document.querySelectorAll("[data-home]").forEach(el=>el.onclick=()=>{state.sessionId++;state.answerQueue.splice(0).forEach(item=>item.resolve(false));stopVoiceSession();clearInterval(state.timer);state.view="home";home()})}
const format=s=>`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;
const pageFooter=()=>`<footer class="page-footer"><span class="brand"><b>F</b> FluentLoop</span><p>Practice boldly. Speak naturally.</p><small>Built for AI speaking practice · 2026</small></footer>`;
home();
